version: '3'
services:
  web:
    image: registry.hub.docker.com/vbloise3/hellofargate
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: ec2-tutorial
        awslogs-region: us-east-1
        awslogs-stream-prefix: web
